apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: ddr549kmip88wc
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      minTimeRange: 1m
  
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: "5s"
  
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    uid: ddrvoeexyaupsd