{
 "title": "Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ms", "label": "Docker-Service", "query": { "query": "label_values(name)" } }
  ]
 },
 "panels": [
  {
   "title": "Network Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum without (instance) (rate(container_network_receive_packets_total{name=\"${ms}\"}[$__rate_interval]))",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "FileSystem I/O",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_blkio_device_usage_total{name=\"${ms}\"} / (1000 * 1000)",
     "legendFormat": "{{operation}} - {{id}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{name=\"${ms}\"} [$__rate_interval])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"${ms}\"} / (1024^2)",
     "legendFormat": "container_memory_usage_MB"
    }
   ]
  }
 ]
}